---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[tomcat_test::default]
    verifier:
          inspec_tests:
            - test/integration/default
    attributes: